/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class arc_api_fits_ArcFitsFileJAPI */

#ifndef _Included_arc_api_fits_ArcFitsFileJAPI
#define _Included_arc_api_fits_ArcFitsFileJAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    WriteFile
 * Signature: (Ljava/lang/String;JII)V
 */
JNIEXPORT void JNICALL Java_arc_api_fits_ArcFitsFileJAPI_WriteFile
  (JNIEnv *, jclass, jstring, jlong, jint, jint);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    WriteTextFile
 * Signature: (Ljava/lang/String;JII)V
 */
JNIEXPORT void JNICALL Java_arc_api_fits_ArcFitsFileJAPI_WriteTextFile
  (JNIEnv *, jclass, jstring, jlong, jint, jint);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    GenerateTestDataFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_arc_api_fits_ArcFitsFileJAPI_GenerateTestDataFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    GetHeader
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_arc_api_fits_ArcFitsFileJAPI_GetHeader__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    GetNumberOfFrames
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_arc_api_fits_ArcFitsFileJAPI_GetNumberOfFrames__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    GetRows
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_arc_api_fits_ArcFitsFileJAPI_GetRows__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    GetCols
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_arc_api_fits_ArcFitsFileJAPI_GetCols__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    GetNAxis
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_arc_api_fits_ArcFitsFileJAPI_GetNAxis__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    GetBpp
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_arc_api_fits_ArcFitsFileJAPI_GetBpp__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    GetHeader
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_arc_api_fits_ArcFitsFileJAPI_GetHeader__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    GetNumberOfFrames
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_arc_api_fits_ArcFitsFileJAPI_GetNumberOfFrames__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    GetRows
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_arc_api_fits_ArcFitsFileJAPI_GetRows__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    GetCols
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_arc_api_fits_ArcFitsFileJAPI_GetCols__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    GetNAxis
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_arc_api_fits_ArcFitsFileJAPI_GetNAxis__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    GetBpp
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_arc_api_fits_ArcFitsFileJAPI_GetBpp__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    GenerateTestData
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_arc_api_fits_ArcFitsFileJAPI_GenerateTestData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    ReOpen
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_arc_api_fits_ArcFitsFileJAPI_ReOpen
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    WriteKeyword
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_arc_api_fits_ArcFitsFileJAPI_WriteKeyword
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    WriteComment
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_arc_api_fits_ArcFitsFileJAPI_WriteComment
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    WriteHistory
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_arc_api_fits_ArcFitsFileJAPI_WriteHistory
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    WriteDate
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_arc_api_fits_ArcFitsFileJAPI_WriteDate
  (JNIEnv *, jclass, jstring);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    Create
 * Signature: (Ljava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_arc_api_fits_ArcFitsFileJAPI_Create
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    Open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_arc_api_fits_ArcFitsFileJAPI_Open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    Resize
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_arc_api_fits_ArcFitsFileJAPI_Resize
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    Write
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_arc_api_fits_ArcFitsFileJAPI_Write__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    Write
 * Signature: (JJIII)V
 */
JNIEXPORT void JNICALL Java_arc_api_fits_ArcFitsFileJAPI_Write__JJIII
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    Read
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_arc_api_fits_ArcFitsFileJAPI_Read
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    WriteSubImage
 * Signature: (JIIIIJ)V
 */
JNIEXPORT void JNICALL Java_arc_api_fits_ArcFitsFileJAPI_WriteSubImage
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jlong);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    ReadSubImage
 * Signature: (JIIII)J
 */
JNIEXPORT jlong JNICALL Java_arc_api_fits_ArcFitsFileJAPI_ReadSubImage
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    Create3D
 * Signature: (Ljava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_arc_api_fits_ArcFitsFileJAPI_Create3D
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    Write3D
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_arc_api_fits_ArcFitsFileJAPI_Write3D__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    Write3D
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_arc_api_fits_ArcFitsFileJAPI_Write3D__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    Read3D
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_arc_api_fits_ArcFitsFileJAPI_Read3D
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    Close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_arc_api_fits_ArcFitsFileJAPI_Close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_api_fits_ArcFitsFileJAPI
 * Method:    GetAPIConstants
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_arc_api_fits_ArcFitsFileJAPI_GetAPIConstants
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
