/* DO NOT EDIT THIS FILE - it is machine generated */
#ifdef __APPLE__
	#include <JavaVM/jni.h>
#else
	#include <jni.h>
#endif

/* Header for class arc_api_tiff_ArcTiffFileJAPI */

#ifndef _Included_arc_api_tiff_ArcTiffFileJAPI
#define _Included_arc_api_tiff_ArcTiffFileJAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     arc_api_tiff_ArcTiffFileJAPI
 * Method:    WriteFile
 * Signature: (Ljava/lang/String;JIII)V
 */
JNIEXPORT void JNICALL Java_arc_api_tiff_ArcTiffFileJAPI_WriteFile
  (JNIEnv *, jclass, jstring, jlong, jint, jint, jint);

/*
 * Class:     arc_api_tiff_ArcTiffFileJAPI
 * Method:    Create
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_arc_api_tiff_ArcTiffFileJAPI_Create
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     arc_api_tiff_ArcTiffFileJAPI
 * Method:    Close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_arc_api_tiff_ArcTiffFileJAPI_Close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_api_tiff_ArcTiffFileJAPI
 * Method:    GetRows
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_arc_api_tiff_ArcTiffFileJAPI_GetRows
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_api_tiff_ArcTiffFileJAPI
 * Method:    GetCols
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_arc_api_tiff_ArcTiffFileJAPI_GetCols
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_api_tiff_ArcTiffFileJAPI
 * Method:    GetBpp
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_arc_api_tiff_ArcTiffFileJAPI_GetBpp
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_api_tiff_ArcTiffFileJAPI
 * Method:    Write
 * Signature: (JJIII)V
 */
JNIEXPORT void JNICALL Java_arc_api_tiff_ArcTiffFileJAPI_Write
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint);

/*
 * Class:     arc_api_tiff_ArcTiffFileJAPI
 * Method:    Read
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_arc_api_tiff_ArcTiffFileJAPI_Read
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_api_tiff_ArcTiffFileJAPI
 * Method:    GetAPIConstants
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_arc_api_tiff_ArcTiffFileJAPI_GetAPIConstants
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
