/* DO NOT EDIT THIS FILE - it is machine generated */
#ifdef __APPLE__
	#include <JavaVM/jni.h>
#else
	#include <jni.h>
#endif

/* Header for class arc_api_display_ArcDisplayJAPI */

#ifndef _Included_arc_api_display_ArcDisplayJAPI
#define _Included_arc_api_display_ArcDisplayJAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     arc_api_display_ArcDisplayJAPI
 * Method:    LaunchDisplay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_arc_api_display_ArcDisplayJAPI_LaunchDisplay
  (JNIEnv *, jclass);

/*
 * Class:     arc_api_display_ArcDisplayJAPI
 * Method:    TerminateDisplay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_arc_api_display_ArcDisplayJAPI_TerminateDisplay
  (JNIEnv *, jclass);

/*
 * Class:     arc_api_display_ArcDisplayJAPI
 * Method:    DisplayImage
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_arc_api_display_ArcDisplayJAPI_DisplayImage
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
